[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc -D --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.70.0"

[context.branch-deploy]
command = "hugo -D --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.70.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/img/*"
  [headers.values]
  cache-control = "public,max-age=604800"

[[headers]]
  for = "*.png"
  [headers.values]
  cache-control = "public,max-age=604800"

[[headers]]
  for = "*.js"
  [headers.values]
  cache-control = "public,max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
  cache-control = "public,max-age=604800"

[[headers]]
  for = "*.woff"
  [headers.values]
  cache-control = "public,max-age=604800"
